### ISSUE TITLE
No matching version found

### ISSUE THREAD

**Issue by aneeshpanoli** [Knowledge-Graph-Hub/kg-covid-19#61] opened 2020-04-01 03:11 UTC
pip install kg_emerging_viruses gives the following error
`
ERROR: Could not find a version that satisfies the requirement kg_emerging_viruses (from versions: none)
ERROR: No matching distribution found for kg_emerging_viruses`

I am on arm64 with Termux, venv python3.6

**Comment by justaddcoffee** [comment] 2020-04-01 03:57
sorry, the instruction (`pip install kg_emerging_viruses`) on the README is incorrect, as we haven't released the package yet. 

Could you try the following to download and run the code (assuming you are on *nix and have git installed:

```
git clone https://github.com/Knowledge-Graph-Hub/kg-covid-19.git
cd kg-covid-19
python run.py download
python run.py transform
python run.py load sample-merge-config.yml 
```

**Comment by aneeshpanoli** [comment] 2020-04-02 23:08
Thanks!

requirements.txt is missing the following packages.
- wget
- tqdm
- encodeproject
- obonet
- tabula-py
- bmt

I installed all the missing libraries but now I get the following error.
```
Traceback (most recent call last):
  File "run.py", line 8, in <module>
    from kg_covid_19.load_utils.merge_kg import load_and_merge
  File "/home/aneesh/Projects/covidgraph/kg-covid-19/kg_covid_19/load_utils/merge_kg.py", line 5, in <module>
    from kgx import Transformer, NeoTransformer
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/kgx/__init__.py", line 10, in <module>
    from kgx.transformers.rdf_transformer import RdfTransformer, ObanRdfTransformer, RdfOwlTransformer
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/kgx/transformers/rdf_transformer.py", line 11, in <module>
    from kgx.transformers.rdf_graph_mixin import RdfGraphMixin
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/kgx/transformers/rdf_graph_mixin.py", line 8, in <module>
    from kgx.utils.rdf_utils import property_mapping, process_iri, make_curie, is_property_multivalued
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/kgx/utils/rdf_utils.py", line 10, in <module>
    toolkit = get_toolkit()
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/kgx/utils/kgx_utils.py", line 142, in get_toolkit
    toolkit = Toolkit()
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/bmt/__init__.py", line 38, in __init__
    self.generator = ToolkitGenerator(schema)
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/bmt/toolkit_generator.py", line 16, in __init__
    super().__init__(schema, None)
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/metamodel/utils/generator.py", line 29, in __init__
    self.schema = schema if isinstance(schema, SchemaDefinition) else SchemaLoader(schema).resolve()
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/metamodel/utils/schemaloader.py", line 13, in __init__
    self.schema = load_raw_schema(data, base_dir=base_dir)
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/metamodel/utils/loadschema.py", line 36, in load_raw_schema
    return load_raw_schema(response)
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/metamodel/utils/loadschema.py", line 51, in load_raw_schema
    for sname, sdef in {k: SchemaDefinition(name=k, **v) for k, v in schemadefs.items()}.items():
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/metamodel/utils/loadschema.py", line 51, in <dictcomp>
    for sname, sdef in {k: SchemaDefinition(name=k, **v) for k, v in schemadefs.items()}.items():
TypeError: __init__() got an unexpected keyword argument 'default_range'

```

**Comment by justaddcoffee** [comment] 2020-04-02 23:49
> requirements.txt is missing the following packages.

I believe that all these are specified in `setup.py`, so 
`python setup.py install --user`
should install them. (Sorry, this also needs to go in the README.)

> I installed all the missing libraries but now I get the following error.
```
[snip]
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/metamodel/utils/loadschema.py", line 51, in <dictcomp>
    for sname, sdef in {k: SchemaDefinition(name=k, **v) for k, v in schemadefs.items()}.items():
TypeError: __init__() got an unexpected keyword argument 'default_range'
```
I've seeing something similar. This seems to be because one or more files needed by one of the dependencies (`bmt`) can't be retrieved (oddly enough from github). 

If you open `run.py` and comment this line:
`from kg_covid_19.load_utils.merge_kg import load_and_merge`
then 
```
run.py download
run.py transform
```
should work. I think `load` should also work once the GH problem is fixed and you uncomment that line.

**Comment by aneeshpanoli** [comment] 2020-04-03 16:17
I am at the last step,  `python run.py load`


```
python run.py load
Usage: run.py load [OPTIONS] YAML
Try 'run.py load --help' for help.

Error: Missing argument 'YAML'.
```


I solved the above error by pointing to the yaml installation

Then I got the error below


```
Traceback (most recent call last):
  File "run.py", line 80, in <module>
    cli()
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "run.py", line 76, in load
    load_and_merge(yaml)
NameError: name 'load_and_merge' is not defined

```


So, I uncommented the import line.

Now I get the same warning as before:


```
Traceback (most recent call last):
  File "run.py", line 8, in <module>
    from kg_covid_19.load_utils.merge_kg import load_and_merge
  File "/home/aneesh/Projects/covidgraph/kg-covid-19/kg_covid_19/load_utils/merge_kg.py", line 5, in <module>
    from kgx import Transformer, NeoTransformer
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/kgx/__init__.py", line 10, in <module>
    from kgx.transformers.rdf_transformer import RdfTransformer, ObanRdfTransformer, RdfOwlTransformer
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/kgx/transformers/rdf_transformer.py", line 11, in <module>
    from kgx.transformers.rdf_graph_mixin import RdfGraphMixin
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/kgx/transformers/rdf_graph_mixin.py", line 8, in <module>
    from kgx.utils.rdf_utils import property_mapping, process_iri, make_curie, is_property_multivalued
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/kgx/utils/rdf_utils.py", line 10, in <module>
    toolkit = get_toolkit()
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/kgx/utils/kgx_utils.py", line 142, in get_toolkit
    toolkit = Toolkit()
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/bmt/__init__.py", line 38, in __init__
    self.generator = ToolkitGenerator(schema)
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/bmt/toolkit_generator.py", line 16, in __init__
    super().__init__(schema, None)
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/metamodel/utils/generator.py", line 29, in __init__
    self.schema = schema if isinstance(schema, SchemaDefinition) else SchemaLoader(schema).resolve()
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/metamodel/utils/schemaloader.py", line 13, in __init__
    self.schema = load_raw_schema(data, base_dir=base_dir)
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/metamodel/utils/loadschema.py", line 36, in load_raw_schema
    return load_raw_schema(response)
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/metamodel/utils/loadschema.py", line 51, in load_raw_schema
    for sname, sdef in {k: SchemaDefinition(name=k, **v) for k, v in schemadefs.items()}.items():
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/metamodel/utils/loadschema.py", line 51, in <dictcomp>
    for sname, sdef in {k: SchemaDefinition(name=k, **v) for k, v in schemadefs.items()}.items():
TypeError: __init__() got an unexpected keyword argument 'default_range'
```

**Comment by justaddcoffee** [comment] 2020-04-03 16:57
```
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/metamodel/utils/loadschema.py", line 51, in load_raw_schema
    for sname, sdef in {k: SchemaDefinition(name=k, **v) for k, v in schemadefs.items()}.items():
  File "/home/aneesh/Projects/covidgraph/lib/python3.6/site-packages/metamodel/utils/loadschema.py", line 51, in <dictcomp>
    for sname, sdef in {k: SchemaDefinition(name=k, **v) for k, v in schemadefs.items()}.items():
TypeError: __init__() got an unexpected keyword argument 'default_range'
```

This error seems to be caused by a problem in the dependencies for `kgx`. I solved this problem just now with a fresh install of all the dependencies. 

Could you try uninstalling and reinstalling `kgx`, `bmt` and `metamodel` (using whichever packaging tool you are using)? 

Also @deepakunni3, any advice here?

**Comment by LucaCappelletti94** [comment] 2020-04-03 17:56
The issue is with the bmt package installed under python 3.6 I think, @deepakunni3 told us in the call from last week that python 3.7 was required.

**Comment by deepakunni3** [comment] 2020-04-03 18:03
Thanks @LucaCappelletti94 ! 

@aneeshpanoli Yes, you would need Python 3.7+ since this repo depends on packages that require Python 3.7+

**Comment by justaddcoffee** [comment] 2020-04-05 20:08
@aneeshpanoli curious if using Python 3.7 resolved your issue?

**Comment by aneeshpanoli** [comment] 2020-04-06 05:03
I  can confirm that  `python setup.py install --user` doesn't install the missing packages. I created a new python 3.7 venv (Python 3.7.7), the load phase was fine but now stuck at transform.
```
INFO:root:Skipping item that doesn't refer to UNIPROT gene
[ttd.py][                 run] INFO: Skipping item that doesn't refer to UNIPROT gene
INFO:root:Parsing StringTransform
[transform.py][           transform] INFO: Parsing StringTransform

```
It's been over 14hrs now. I doubt if that's normal. Maybe I am missing something?

**Comment by deepakunni3** [comment] 2020-04-06 05:06
@aneeshpanoli We fixed an issue with the `StringTransform`. If you do a `git pull` to fetch the latest changes, that transform should take only 10-15 mins.

**Comment by aneeshpanoli** [comment] 2020-04-06 07:22
Thanks! I now have a transform folder with all the tsvs and a new merged_kg.tar. However, I have a memory issue.

```
python run.py load
WARNING:ToolkitGenerator:class "pairwise interaction association" slot "interacting molecules category" does not reference an existing slot.  New slot was created.
WARNING:ToolkitGenerator:Unrecognized prefix: SEMMEDDB
WARNING:ToolkitGenerator:Unrecognized prefix: WD
WARNING:ToolkitGenerator:Unrecognized prefix: dct
WARNING:ToolkitGenerator:Unrecognized prefix: ExO
WARNING:ToolkitGenerator:Unrecognized prefix: HANCESTRO
WARNING:ToolkitGenerator:Unrecognized prefix: BioSample
WARNING:ToolkitGenerator:Unrecognized prefix: PUBCHEM
WARNING:ToolkitGenerator:Unrecognized prefix: GTOPDB
WARNING:ToolkitGenerator:Unrecognized prefix: IUPHAR
WARNING:ToolkitGenerator:Unrecognized prefix: UNIPROTKB
WARNING:ToolkitGenerator:Unrecognized prefix: RNAcentral
WARNING:ToolkitGenerator:Unrecognized prefix: IntAct
WARNING:ToolkitGenerator:Unrecognized prefix: Reactome
WARNING:ToolkitGenerator:Unrecognized prefix: VMC
WARNING:ToolkitGenerator:Unrecognized prefix: CAID
WARNING:ToolkitGenerator:Unrecognized prefix: CIViC
WARNING:ToolkitGenerator:Unrecognized prefix: HGVS
WARNING:ToolkitGenerator:Unrecognized prefix: MYVARIANT_HG19
WARNING:ToolkitGenerator:Unrecognized prefix: MYVARIANT_HG38
WARNING:ToolkitGenerator:Unrecognized prefix: ECTO
WARNING:ToolkitGenerator:Unrecognized prefix: PHARMGKB
{'type': 'tsv', 'filename': ['data/transformed/drug_central/nodes.tsv', 'data/transformed/drug_central/edges.tsv']}
INFO:root:Loading drug-central
[merge_kg.py][      load_and_merge] INFO: Loading drug-central
{'type': 'tsv', 'filename': ['data/transformed/hpo/nodes.tsv', 'data/transformed/hpo/edges.tsv']}
INFO:root:Loading hpo
[merge_kg.py][      load_and_merge] INFO: Loading hpo
{'type': 'tsv', 'filename': ['data/transformed/pharmgkb/nodes.tsv', 'data/transformed/pharmgkb/edges.tsv']}
INFO:root:Loading pharmgkb
[merge_kg.py][      load_and_merge] INFO: Loading pharmgkb
{'type': 'tsv', 'filename': ['data/transformed/STRING/nodes.tsv', 'data/transformed/STRING/edges.tsv']}
INFO:root:Loading STRING
[merge_kg.py][      load_and_merge] INFO: Loading STRING

```
I've 16gis on my machine, which starts to fill up as soon as the script hits  `STRING/edges.tsv'`. The largest .tsv, if I'm right, is the `STRING/edges.tsv` ~1.2G. That doesn't explain the memory usage. What am I missing here?

**Comment by justaddcoffee** [comment] 2020-04-07 21:32
> That doesn't explain the memory usage. What am I missing here?

Well, for now memory requirements might be a bit high until the load/merge step is optimized for mem usage. 

Closing this ticket, but feel free to make another for any lingering issues you encounter.

**Closed by justaddcoffee** 2020-04-07 21:32 UTC
Labels: documentation
