### ISSUE TITLE
Installing the requirements file doesn't work

### ISSUE THREAD

**Issue by Leoningel** [Knowledge-Graph-Hub/kg-covid-19#402] opened 2021-03-05 13:49 UTC
### Describe the bug
When running pip install -r requirements.txt it gives me an error.

### To Reproduce

Run pip install -r requirements.txt in the main directory.

## Expected behavior

That the requirements would be installed

### Version

1.0.0

### Additional context

The error comes with exit status 128. The issue seems to be solved here: https://stackoverflow.com/questions/58424348/pip-cannot-clone-from-https-anymore-error-128. Changing the command git+git://github.com/deepakunni3/kgx@kg-covid-19 to git+https://github.com/deepakunni3/kgx@kg-covid-19 worked for me.

**Comment by justaddcoffee** [comment] 2021-03-06 03:56
Thanks for the bug report. I can't reproduce this issue though. I'm puzzled by why git protocol isn't working on your end.

Could you post the output of `pip install -r requirements.txt`?

**Comment by Leoningel** [comment] 2021-03-06 10:09
Hi @justaddcoffee, thanks for the response. I'm currently trying to reproduce it as well but cannot do it. Maybe it was just a mistake from my end, or some configurations in my git that created the issue. If you've not received similar issues then I'd say we could close this issue.

**Comment by justaddcoffee** [comment] 2021-03-06 10:10
okay, closing, let me know if you run into this again

**Closed by justaddcoffee** 2021-03-06 10:10 UTC
Labels: bug
